[package]
name = "rterm-terminal"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
base64 = "0.22"
flate2 = "1"
rterm-types = { path = "../rterm-types", version = "0.1.0" }
smol_str = "0.2"
unicode-normalization = "0.1"
unicode-segmentation = "1"
unicode-width = "0.2"

[dev-dependencies]
proc-macro2 = { version = "1", features = ["span-locations"] }
sha2 = "0.11"
syn = { version = "2", features = ["full", "visit"] }

[lints]
workspace = true
