[package]
name = "rssh-terminal"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
base64 = "0.22"
flate2 = "1"
rssh-core = { path = "../rssh-core", version = "0.1.0" }
smol_str = "0.2"
unicode-normalization = "0.1"
unicode-segmentation = "1"
unicode-width = "0.2"

[lints]
workspace = true
