[package]
name = "rssh-renderer"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rterm-render-core = { path = "../rterm-render-core", version = "0.1.0" }
rterm-render-cpu = { path = "../rterm-render-cpu", version = "0.1.0" }
rterm-render-wgpu = { path = "../rterm-render-wgpu", version = "0.1.0" }

[lints]
workspace = true
