[package]
name = "rssh-native"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rssh-config = { path = "../rssh-config", version = "0.1.0" }
rssh-domain = { path = "../rssh-domain", version = "0.1.0" }
rterm-types = { path = "../rterm-types", version = "0.1.0" }
rssh-runtime = { path = "../rssh-runtime", version = "0.1.0" }

[lints]
workspace = true
