[package]
name = "rssh-test-support"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
futures = "0.3"
rand = "0.10.1"
russh = { version = "0.61.2", default-features = false, features = ["flate2", "ring"] }
russh-sftp = "2.3.0"
tempfile = "3"
tokio = { version = "1", features = ["io-util", "net", "rt-multi-thread", "sync", "time"] }

[target.'cfg(windows)'.dev-dependencies]
junction = { version = "2.0.0", default-features = false }

[lints]
workspace = true
