[package]
name = "rssh-ssh"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
russh = { version = "0.61.2", default-features = false, features = ["flate2", "ring"] }
rterm-types = { path = "../rterm-types", version = "0.1.0" }
tokio = { version = "1", features = ["io-util", "net", "rt-multi-thread", "time"] }

[dev-dependencies]
rssh-test-support = { path = "../rssh-test-support", version = "0.1.0" }

[lints]
workspace = true
