[package]
name = "rssh-app"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arboard = "3"
base64 = "0.22"
crossterm = "0.29"
notify = "8"
pollster = "0.4"
regex = "1"
rpassword = "7"
rssh-core = { path = "../rssh-core" }
rssh-fonts = { path = "../rssh-fonts" }
rssh-pty = { path = "../rssh-pty" }
rssh-renderer = { path = "../rssh-renderer" }
rssh-ssh = { path = "../rssh-ssh" }
rssh-terminal = { path = "../rssh-terminal" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = { version = "=0.36.1", default-features = false, features = ["system"] }
toml = "0.8"
unicode_names2 = "3.1"
unicode-normalization = "0.1"
unicode-segmentation = "1"
unicode-width = "0.2"
wezterm-color-types = "=0.3.0"
winit = "0.30"

[dev-dependencies]
rssh-test-support = { path = "../rssh-test-support" }
sha2 = "0.11"

[lints]
workspace = true
