[package]
name = "rssh-app"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arboard = "3"
base64 = "0.22"
crossterm = "0.29"
pixels = "0.15"
regex = "1"
rpassword = "7"
rssh-core = { path = "../rssh-core" }
rssh-pty = { path = "../rssh-pty" }
rssh-renderer = { path = "../rssh-renderer" }
rssh-ssh = { path = "../rssh-ssh" }
rssh-terminal = { path = "../rssh-terminal" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = { version = "=0.36.1", default-features = false, features = ["system"] }
toml = "0.8"
winit = "0.30"

[dev-dependencies]

[lints]
workspace = true
