[package]
name = "rssh-app"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
crossterm = "0.29"
rssh-pty = { path = "../rssh-pty" }

[dev-dependencies]
rssh-core = { path = "../rssh-core" }
rssh-terminal = { path = "../rssh-terminal" }

[lints]
workspace = true
